### ISSUE TITLE
Protocol - Migrate scraping of datasets to the Subnet as validators jobs

### ISSUE THREAD

**Issue by giovaroma** [masa-finance/masa-oracle#464] opened 2024-07-29 20:47 UTC
Problem: As we continue to add solutions from a product strategy perspective scraping on-demand and leveraging the protocol to mitigate scraping of datasets by miners in the subnet will be important to allow users to access robust datasets and updated. 

Acceptance criteria WIP.

**Comment by giovaroma** [comment] 2024-08-06 16:30
Need help here with an acceptance criteria @teslashibe.

**Comment by Luka-Loncar** [comment] 2024-09-16 16:44
It is a duplicate of indexing twitter data

**Closed by Luka-Loncar** 2024-09-16 16:44 UTC
Labels: wontfix
